### PR TITLE
Safe navigate the first node's `sym?` method

### LINKED ISSUE #21: node_processor.rb line 103 undefined method `sym?`
Ran into the following in a build pipeline:

```
bundler: failed to load command: leftovers (/home/runner/work/myproject/myproject/vendor/bundle/ruby/3.1.0/bin/leftovers)
/home/runner/work/myproject/myproject/vendor/bundle/ruby/3.1.0/gems/leftovers-0.11.2/lib/leftovers/file_collector/node_processor.rb:103:in `on_block_pass': undefined method `sym?' for nil:NilClass (NoMethodError)
	from /home/runner/work/myproject/myproject/vendor/bundle/ruby/3.1.0/gems/ast-2.4.2/lib/ast/processor/mixin.rb:259:in `process'
	from /home/runner/work/myproject/myproject/vendor/bundle/ruby/3.1.0/gems/ast-2.4.2/lib/ast/processor/mixin.rb:276:in `block in process_all'
	from /home/runner/work/myproject/myproject/vendor/bundle/ruby/3.1.0/gems/ast-2.4.2/lib/ast/processor/mixin.rb:275:in `map'
	from /home/runner/work/myproject/myproject/vendor/bundle/ruby/3.1.0/gems/ast-2.4.2/lib/ast/processor/mixin.rb:275:in `process_all'
	from /home/runner/work/myproject/myproject/vendor/bundle/ruby/3.1.0/gems/parser-3.1.2.1/lib/parser/ast/processor.rb:181:in `on_send'
```

### PR DESCRIPTION
**Pull request by sclarson**
fixes #21 

This line was causing a nil reference in a build pipeline.

### CODE REVIEW

**Comment by robotdana** [comment]
hi thank you

are you able to add a test for this?

**Comment by sclarson** [comment]
> hi thank you
> 
> are you able to add a test for this?

I'll look at the diff that started the break and see if I can.

**Comment by robotdana** [comment]
Hi i've just created a new release which should point to the code that leftovers is tripping up on, e.g. 
```
Leftovers::FileCollector::Error: ErrorClass: original error message
   when processing node at app/foo.rb:line:column

backtrace
```

if that helps with finding the code that leftovers broke on

**Comment by orien** [comment]
I experienced a similar error when introducing [anonymous block forwarding](https://docs.rubocop.org/rubocop/cops_naming.html#namingblockforwarding) to a code base.

**Comment by robotdana** [comment]
thanks orien i should be able to fix this some time this week, and maybe i’ll see you at rubyconf?

**Comment by robotdana** [comment]
Thanks for raising this, it should be fixed with newly released 0.12.1. feel free to reopen this if it isn't.

**Comment by orien** [comment]
@robotdana Thanks!

I wish you a fantastic time at RubyConf. Unfortunately, I can't make it.

**Pull request closed without merging**
